# Generated by Django 4.2.1 on 2023-05-22 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/main-image/', verbose_name='Основная фотография'),
            preserve_default=False,
        ),
    ]
